class Wall(Entity):
	"""docstring for Wall"""
	def __init__(self,screen,pos,nb):
		filename = "wall.bnp"
		super().__init__(screen,filename,pos)


class Red(self):
	"""docstring for Red"""
	def __init__(self,red,):
		filename = "red.bnp"
		super().__init__(screen,filename,pos)
			

class Green(self):
	"""docstring for green"""
	def __init__(self, green):
		filename = "green.bnp"
		super().__init__(screen,filename,pos)

class Exit(self):
	"""docstring for Exit"""
	def __init__(self,exit):
		filename = "exit.bnp"
		super().__init__(screen,filename,pos)
